apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: clutch-ingress-super-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  project: cpaas
  source:
    path: ingress/argo-apps/
    plugin:
      name: argocd-vault-plugin
    repoURL: git@github.com:KrishnaSindhur/clutch-main
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
