apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: test-service-super-app
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: default
  project: test-service
  source:
    path: products/test-service/manifests/argo-apps/
    plugin:
      name: argocd-vault-plugin
    repoURL: git@github.com:KrishnaSindhur/clutch-test2
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
    syncOptions:
      - FailOnSharedResource=true
